Traceback (most recent call last):
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import LISC code
from lisc import Counts, Counts1D
from lisc.collect import collect_info, collect_across_time
from lisc.io import (save_meta_data, load_meta_data, save_object, load_object,
                     save_time_results, load_time_results)
from lisc.plts.counts import plot_matrix, plot_vector
from lisc.plts.time import plot_results_across_years
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-3b825db83a8a>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Import LISC code[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mfrom[0m [0mlisc[0m [0;32mimport[0m [0mCounts[0m[0;34m,[0m [0mCounts1D[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;32mfrom[0m [0mlisc[0m[0;34m.[0m[0mcollect[0m [0;32mimport[0m [0mcollect_info[0m[0;34m,[0m [0mcollect_across_time[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m from lisc.io import (save_meta_data, load_meta_data, save_object, load_object,
[1;32m      5[0m                      save_time_results, load_time_results)

[0;31mModuleNotFoundError[0m: No module named 'lisc'
ModuleNotFoundError: No module named 'lisc'

