Traceback (most recent call last):
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from neurodsp.sim import (sim_powerlaw, sim_synaptic_current, sim_knee,
                          sim_oscillation, sim_combined, sim_peak_oscillation)
from neurodsp.utils import set_random_seed
from neurodsp.plts import plot_time_series, plot_timeseries_and_spectra
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-2fe5dbab9c62>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m                           sim_oscillation, sim_combined, sim_peak_oscillation)
[1;32m      3[0m [0;32mfrom[0m [0mneurodsp[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mset_random_seed[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0mneurodsp[0m[0;34m.[0m[0mplts[0m [0;32mimport[0m [0mplot_time_series[0m[0;34m,[0m [0mplot_timeseries_and_spectra[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mImportError[0m: cannot import name 'plot_timeseries_and_spectra' from 'neurodsp.plts' (/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/neurodsp/plts/__init__.py)
ImportError: cannot import name 'plot_timeseries_and_spectra' from 'neurodsp.plts' (/Users/tom/opt/anaconda3/envs/book/lib/python3.8/site-packages/neurodsp/plts/__init__.py)

